export const productType = {
  GET_ALL_PRODUCTS_START: "GET_ALL_PRODUCTS_START",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_ERROR: "GET_ALL_PRODUCTS_ERROR",

  GET_FILTER_PRODUCT_START: "GET_FILTER_PRODUCT_START",
  GET_FILTER_PRODUCT_SUCCESS: "GET_FILTER_PRODUCT_SUCCESS",
  GET_FILTER_PRODUCT_ERROR: "GET_FILTER_PRODUCT_ERROR",
};

export const filterType = {
  CHANGE_FILTER_CATEGORY_LV0: "CHANGE_FILTER_CATEGORY_LV0",
  CHANGE_FILTER_CATEGORY_LV1: "CHANGE_FILTER_CATEGORY_LV1",
  CHANGE_FILTER_SEARCH: "CHANGE_FILTER_SEARCH",
  CHANGE_FILTER_PAGINATION: "CHANGE_FILTER_PAGINATION",
};

export const orderType = {
  GET_ALL_ORDER_START: "GET_ALL_ORDER_START",
  GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
  GET_ALL_ORDER_ERROR: "GET_ALL_ORDER_ERROR",

  GET_FILTER_ORDER_START: "GET_FILTER_PRODUCT_START",
  GET_FILTER_ORDER_SUCCESS: "GET_FILTER_PRODUCT_SUCCESS",
  GET_FILTER_ORDER_ERROR: "GET_FILTER_PRODUCT_ERROR",
};
