export const productType = {
  GET_ALL_PRODUCTS_START: "GET_ALL_PRODUCTS_START",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_ERROR: "GET_ALL_PRODUCTS_ERROR",

  GET_FILTER_PRODUCT_START: "GET_FILTER_PRODUCT_START",
  GET_FILTER_PRODUCT_SUCCESS: "GET_FILTER_PRODUCT_SUCCESS",
  GET_FILTER_PRODUCT_ERROR: "GET_FILTER_PRODUCT_ERROR",
};

export const productDetail = {
  GET_PRODUCT_DETAILS_START: "GET_PRODUCT_DETAILS_START",
  GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
  GET_PRODUCT_DETAILS_ERROR: "GET_PRODUCT_DETAILS_ERROR",
};

export const filterType = {
  CHANGE_FILTER_CATEGORY_LV0: "CHANGE_FILTER_CATEGORY_LV0",
  CHANGE_FILTER_CATEGORY_LV1: "CHANGE_FILTER_CATEGORY_LV1",
  CHANGE_FILTER_SEARCH: "CHANGE_FILTER_SEARCH",
  CHANGE_FILTER_PAGINATION: "CHANGE_FILTER_PAGINATION",
};

export const orderType = {
  GET_ALL_ORDER_START: "GET_ALL_ORDER_START",
  GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
  GET_ALL_ORDER_ERROR: "GET_ALL_ORDER_ERROR",

  GET_FILTER_ORDER_START: "GET_FILTER_PRODUCT_START",
  GET_FILTER_ORDER_SUCCESS: "GET_FILTER_PRODUCT_SUCCESS",
  GET_FILTER_ORDER_ERROR: "GET_FILTER_PRODUCT_ERROR",
};

export const cartType = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CHANGE_QUANTITY_CART: "CHANGE_QUANTITY_CART",
  CLEAR_ALL_CART: "CLEAR_ALL_CART",
};

export const authTypes = {
  CUSTOMER_LOGIN_START: "CUSTOMER_LOGIN_START",
  CUSTOMER_LOGIN_SUCCESS: "CUSTOM_LOGIN_SUCCESS",
  CUSTOMER_LOGIN_FAILURE: "CUSTOMER_LOGIN_FAILURE",

  CUSTOMER_LOGOUT: "CUSTOMER_LOGOUT",

  GET_CUSTOMER_PROFILE_START: "GET_CUSTOMER_PROFILE_START",
  GET_CUSTOMER_PROFILE_SUCCESS: "GET_CUSTOMER_PROFILE_SUCCESS",
  GET_CUSTOMER_PROFILE_FAILURE: "GET_CUSTOMER_PROFILE_FAILURE",
};

export const customerType = {
  CREAT_CUSTOMER_START: "CREAT_CUSTOMER_START",
  CREAT_CUSTOMER_SUCCESS: "CREAT_CUSTOMER_SUCCESS",
  CREAT_CUSTOMER_FAILURE: "CREAT_CUSTOMER_FAILURE",
  UPDATE_CUSTOMER_START: "UPDATE_CUSTOMER_START",
  UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_FAILURE: "UPDATE_CUSTOMER_FAILURE",
};
